modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["dev", "web", "game", "draw", "5", "6", "vid", "vm", "dl", "social"]
layouts = [
    "MainAndVertStack",
    "MainAndHorizontalStack",
    "MainAndDeck",
    #"GridHorizontal",
    #"EvenHorizontal",
    #"EvenVertical",
    "Fibonacci",
    #"CenterMain",
    #"CenterMainBalanced",
    "Monocle",
    #"RightWiderLeftStack",
    #"LeftWiderRightStack",
]
disable_current_tag_swap = true
#focus_behaviour = "Driven"
#focus_behaviour = "ClickTo"
focus_behaviour = "Sloppy"
sloppy_mouse_follows_focus = false
focus_new_windows = true
layout_mode = "Tag"

scratchpad = [
    { name = "Alacritty", value = "alacritty" },
    { name = "htop", value = "alacritty -e htop", x = 100, y = 100, width = 1000, height = 600 },
]

window_rules = [
    { window_class = "Steam", spawn_on_tag = 5 },
]

keybind = [
    { command = "Execute", value = "rofi -show drun", modifier = ["modkey"], key = "d" },
    { command = "Execute", value = "alacritty", modifier = ["modkey"], key = "Return" },
    #{ command = "Execute", value = "maim -suB | tee ~/Images/Screenshots/$(date +%s).png | xclip -t image/png -selection clipboard", modifier = ["modkey", "Shift"], key = "s" },
    { command = "ToggleScratchPad", value = "Alacritty", modifier = ["modkey"], key = "s" },
    { command = "ToggleScratchPad", value = "htop", modifier = ["modkey"], key = "F1" },

    # WM control
    { command = "CloseWindow", modifier = ["modkey", "Shift"], key = "q" },
    { command = "SoftReload", modifier = ["modkey", "Shift"], key = "r" },
    { command = "Execute", value = "loginctl kill-session $XDG_SESSION_ID", modifier = ["modkey", "Shift"], key = "x" },
    { command = "SwapTags", modifier = ["modkey"], key = "w" },

    # Window control
    { command = "MoveWindowUp", modifier = ["modkey", "Shift"], key = "Up" },
    { command = "MoveWindowUp", modifier = ["modkey", "Shift"], key = "k" },
    { command = "MoveWindowDown", modifier = ["modkey", "Shift"], key = "Down" },
    { command = "MoveWindowDown", modifier = ["modkey", "Shift"], key = "j" },
    { command = "MoveWindowTop", modifier = ["modkey", "Shift"], key = "Return" },
    { command = "ToggleFullScreen", modifier = ["modkey"], key = "f" },
    { command = "ToggleFloating", modifier = ["modkey", "Shift"], key = "space" },
    { command = "FocusWindowUp", modifier = ["modkey"], key = "Up" },
    { command = "FocusWindowUp", modifier = ["modkey"], key = "k" },
    { command = "FocusWindowDown", modifier = ["modkey"], key = "Down" },
    { command = "FocusWindowDown", modifier = ["modkey"], key = "j" },
    { command = "IncreaseMainWidth", value = "5", modifier = ["modkey", "Control"], key = "Up" },
    { command = "IncreaseMainWidth", value = "5", modifier = ["modkey"], key = "l" },
    { command = "DecreaseMainWidth", value = "5", modifier = ["modkey", "Control"], key = "Down" },
    { command = "DecreaseMainWidth", value = "5", modifier = ["modkey"], key = "h" },

    # Tags and Layouts control
    { command = "NextLayout", modifier = ["modkey"], key = "equal" },
    { command = "PreviousLayout", modifier = ["modkey"], key = "parenright" },
    { command = "GotoTag", value = "1", modifier = ["modkey"], key = "ampersand" },
    { command = "GotoTag", value = "2", modifier = ["modkey"], key = "eacute" },
    { command = "GotoTag", value = "3", modifier = ["modkey"], key = "quotedbl" },
    { command = "GotoTag", value = "4", modifier = ["modkey"], key = "apostrophe" },
    { command = "GotoTag", value = "5", modifier = ["modkey"], key = "parenleft" },
    { command = "GotoTag", value = "6", modifier = ["modkey"], key = "minus" },
    { command = "GotoTag", value = "7", modifier = ["modkey"], key = "egrave" },
    { command = "GotoTag", value = "8", modifier = ["modkey"], key = "underscore" },
    { command = "GotoTag", value = "9", modifier = ["modkey"], key = "ccedilla" },
    { command = "GotoTag", value = "10", modifier = ["modkey"], key = "dollar" },
    { command = "MoveToTag", value = "1", modifier = ["modkey", "Shift"], key = "ampersand" },
    { command = "MoveToTag", value = "2", modifier = ["modkey", "Shift"], key = "eacute" },
    { command = "MoveToTag", value = "3", modifier = ["modkey", "Shift"], key = "quotedbl" },
    { command = "MoveToTag", value = "4", modifier = ["modkey", "Shift"], key = "apostrophe" },
    { command = "MoveToTag", value = "5", modifier = ["modkey", "Shift"], key = "parenleft" },
    { command = "MoveToTag", value = "6", modifier = ["modkey", "Shift"], key = "minus" },
    { command = "MoveToTag", value = "7", modifier = ["modkey", "Shift"], key = "egrave" },
    { command = "MoveToTag", value = "8", modifier = ["modkey", "Shift"], key = "underscore" },
    { command = "MoveToTag", value = "9", modifier = ["modkey", "Shift"], key = "ccedilla" },
    { command = "MoveToTag", value = "10", modifier = ["modkey", "Shift"], key = "dollar" },
]
