[colors]
# background = "#2e2e38"
# foreground = "#c7c7d1"

[font]
size = 10

[font.bold]
family = "IosevkaTerm NF"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm NF"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm NF"
style = "Italic"

[font.normal]
family = "IosevkaTerm NF"
style = "Regular"

[font.offset]
x = 1

[window]
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 10
y = 9
