#!/bin/sh

# My tablet configuration for Wacom Intuos S

# Button mappings
map()
{
    xsetwacom set "Wacom Intuos S Pad pad" Button "$@"
}
map 1 "key control z"
map 3 "key f1"
map 8 "key f2"

# Area setup
tablet_cmd()
{
    xsetwacom set "Wacom Intuos S Pen stylus" "$@"
}
# xsetwacom set "Wacom Intuos S Pen stylus" Area 0 0 15200 9500
# [ "$1" = "osu" ] && xsetwacom set "Wacom Intuos S Pen stylus" Area 3800 2613 11400 6888
# [ "$1" = "osu-topleft" ] && xsetwacom set "Wacom Intuos S Pen stylus" Area 0 0 7600 4275
if [ "$1" = "osu" ]; then
    tablet_cmd Area 0 0 7600 4275
else
    tablet_cmd Area 0 0 15200 9500
fi
